#
# This file is autogenerated by pip-compile with python 3.9
# To update, run:
#
#    pip-compile --output-file=requirements/requirements.common.txt setup.py

google-api-python-client
google-auth-httplib2
google-auth-oauthlib